-- QuickDrop Database Schema
-- Smart Visual Knowledge Manager

-- Users table
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE,
  display_name TEXT,
  avatar_url TEXT,
  bio TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER
);

CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email ON users(email);

-- Screenshots with AI-enhanced metadata
CREATE TABLE IF NOT EXISTS screenshots (
  id TEXT PRIMARY KEY,
  user_id TEXT,

  -- File info
  filename TEXT NOT NULL,
  link TEXT NOT NULL,
  thumbnail_url TEXT,
  file_size INTEGER,
  mime_type TEXT,

  -- AI-generated metadata (populated asynchronously)
  ai_title TEXT,              -- "MongoDB Connection Error on Port 27017"
  ai_tags TEXT,               -- "database,error,mongodb,nodejs,backend"
  ai_category TEXT,           -- "bug-report" | "tutorial" | "note" | "code" | "design" | "other"
  ai_description TEXT,        -- Detailed 2-3 sentence summary
  ai_confidence REAL,         -- 0-1 confidence score
  ai_processed BOOLEAN DEFAULT 0,

  -- OCR extracted data
  ocr_text TEXT,
  ocr_language TEXT,
  detected_urls TEXT,         -- JSON array: ["https://...", "https://..."]
  entities TEXT,              -- JSON object: {"names": [...], "dates": [...], "numbers": [...]}

  -- User metadata
  user_title TEXT,            -- User can override AI title
  user_tags TEXT,             -- User can add custom tags
  user_description TEXT,      -- User can add notes

  -- Settings
  expiry_hours INTEGER DEFAULT 24,
  expires_at INTEGER,
  is_public BOOLEAN DEFAULT 0,
  is_deleted BOOLEAN DEFAULT 0,

  -- Analytics
  view_count INTEGER DEFAULT 0,
  last_viewed_at INTEGER,

  -- Timestamps
  created_at INTEGER NOT NULL,
  updated_at INTEGER,

  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_screenshots_user ON screenshots(user_id);
CREATE INDEX idx_screenshots_created ON screenshots(created_at DESC);
CREATE INDEX idx_screenshots_expires ON screenshots(expires_at);
CREATE INDEX idx_screenshots_public ON screenshots(is_public, created_at DESC);
CREATE INDEX idx_screenshots_category ON screenshots(ai_category, is_public);

-- Full-text search index
CREATE VIRTUAL TABLE IF NOT EXISTS screenshots_fts USING fts5(
  id UNINDEXED,
  ai_title,
  ai_tags,
  ai_description,
  ocr_text,
  filename,
  user_title,
  user_tags,
  user_description,
  content=screenshots,
  content_rowid=rowid
);

-- Triggers to keep FTS index in sync
CREATE TRIGGER IF NOT EXISTS screenshots_ai_insert AFTER INSERT ON screenshots BEGIN
  INSERT INTO screenshots_fts(rowid, id, ai_title, ai_tags, ai_description, ocr_text, filename, user_title, user_tags, user_description)
  VALUES (new.rowid, new.id, new.ai_title, new.ai_tags, new.ai_description, new.ocr_text, new.filename, new.user_title, new.user_tags, new.user_description);
END;

CREATE TRIGGER IF NOT EXISTS screenshots_au_update AFTER UPDATE ON screenshots BEGIN
  UPDATE screenshots_fts SET
    ai_title = new.ai_title,
    ai_tags = new.ai_tags,
    ai_description = new.ai_description,
    ocr_text = new.ocr_text,
    filename = new.filename,
    user_title = new.user_title,
    user_tags = new.user_tags,
    user_description = new.user_description
  WHERE rowid = new.rowid;
END;

CREATE TRIGGER IF NOT EXISTS screenshots_ad_delete AFTER DELETE ON screenshots BEGIN
  DELETE FROM screenshots_fts WHERE rowid = old.rowid;
END;

-- Collections (organize screenshots into folders/boards)
CREATE TABLE IF NOT EXISTS collections (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  color TEXT,                 -- Hex color for UI
  icon TEXT,                  -- Icon name
  is_public BOOLEAN DEFAULT 0,
  is_auto BOOLEAN DEFAULT 0,  -- Auto-generated by AI
  auto_rule TEXT,             -- JSON: AI rule for auto-collection
  item_count INTEGER DEFAULT 0,
  view_count INTEGER DEFAULT 0,
  created_at INTEGER NOT NULL,
  updated_at INTEGER,

  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_collections_user ON collections(user_id);
CREATE INDEX idx_collections_public ON collections(is_public, updated_at DESC);

-- Collection items (many-to-many)
CREATE TABLE IF NOT EXISTS collection_items (
  collection_id TEXT NOT NULL,
  screenshot_id TEXT NOT NULL,
  position INTEGER DEFAULT 0,  -- For manual ordering
  added_at INTEGER NOT NULL,
  added_by TEXT,               -- User ID who added (for shared collections)

  PRIMARY KEY(collection_id, screenshot_id),
  FOREIGN KEY(collection_id) REFERENCES collections(id) ON DELETE CASCADE,
  FOREIGN KEY(screenshot_id) REFERENCES screenshots(id) ON DELETE CASCADE
);

CREATE INDEX idx_collection_items_screenshot ON collection_items(screenshot_id);

-- Comments (for public screenshots)
CREATE TABLE IF NOT EXISTS comments (
  id TEXT PRIMARY KEY,
  screenshot_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  parent_id TEXT,             -- For nested replies
  content TEXT NOT NULL,
  is_edited BOOLEAN DEFAULT 0,
  is_deleted BOOLEAN DEFAULT 0,
  created_at INTEGER NOT NULL,
  updated_at INTEGER,

  FOREIGN KEY(screenshot_id) REFERENCES screenshots(id) ON DELETE CASCADE,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY(parent_id) REFERENCES comments(id) ON DELETE CASCADE
);

CREATE INDEX idx_comments_screenshot ON comments(screenshot_id, created_at);
CREATE INDEX idx_comments_user ON comments(user_id);

-- Likes (for public screenshots)
CREATE TABLE IF NOT EXISTS likes (
  screenshot_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  created_at INTEGER NOT NULL,

  PRIMARY KEY(screenshot_id, user_id),
  FOREIGN KEY(screenshot_id) REFERENCES screenshots(id) ON DELETE CASCADE,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_likes_screenshot ON likes(screenshot_id);
CREATE INDEX idx_likes_user ON likes(user_id);

-- Follows (user following system for discovery)
CREATE TABLE IF NOT EXISTS follows (
  follower_id TEXT NOT NULL,
  following_id TEXT NOT NULL,
  created_at INTEGER NOT NULL,

  PRIMARY KEY(follower_id, following_id),
  FOREIGN KEY(follower_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY(following_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_follows_follower ON follows(follower_id);
CREATE INDEX idx_follows_following ON follows(following_id);

-- Activity feed (for homepage/discover)
CREATE TABLE IF NOT EXISTS activity (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  activity_type TEXT NOT NULL,  -- "upload" | "collection" | "comment" | "like"
  screenshot_id TEXT,
  collection_id TEXT,
  comment_id TEXT,
  created_at INTEGER NOT NULL,

  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY(screenshot_id) REFERENCES screenshots(id) ON DELETE CASCADE,
  FOREIGN KEY(collection_id) REFERENCES collections(id) ON DELETE CASCADE
);

CREATE INDEX idx_activity_created ON activity(created_at DESC);
CREATE INDEX idx_activity_user ON activity(user_id, created_at DESC);

-- Tags (for trending tags discovery)
CREATE TABLE IF NOT EXISTS tags (
  tag TEXT PRIMARY KEY,
  usage_count INTEGER DEFAULT 0,
  last_used_at INTEGER,
  created_at INTEGER NOT NULL
);

CREATE INDEX idx_tags_popular ON tags(usage_count DESC);

-- AI processing queue (track pending AI jobs)
CREATE TABLE IF NOT EXISTS ai_queue (
  screenshot_id TEXT PRIMARY KEY,
  retry_count INTEGER DEFAULT 0,
  error TEXT,
  created_at INTEGER NOT NULL,
  processed_at INTEGER,

  FOREIGN KEY(screenshot_id) REFERENCES screenshots(id) ON DELETE CASCADE
);

CREATE INDEX idx_ai_queue_pending ON ai_queue(processed_at) WHERE processed_at IS NULL;
